[package]
description = "Package bindings for photobooth."
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
license = "AGPL-3.0"
name = "egomoose/photobooth-plugin-bindings"
private = true
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/EgoMoose/photobooth-plugin"
version = "1.2.8"
