asset_dir = "icons/output"
exclude_assets = []
write_dir = "src/Main/UserInterface"

[creator]
type = "user"
id = 2155311

[codegen]
output_name = "Icons"
typescript = false
style = "nested"
strip_extension = true
