[creator]
type = "user"
id = 2155311

[codegen]
typescript = false
style = "nested"
strip_extensions = true

[inputs.assets]
path = "assets/icons/asphalt/**/*"
output_path = "src/Main/UserInterface/Icons"
bleed = true