--!strict

return {
	useMouseDrag = require(script.useMouseDrag),
	useSelection = require(script.useSelection),
	useEditableImage = require(script.useEditableImage),
	useSelectedEditableImage = require(script.useSelectedEditableImage),

	usePhotoFlag = require(script.usePhotoFlag),
	usePhotoConfiguration = require(script.usePhotoConfiguration),

	usePlugin = require(script.usePlugin),
	useIsStoryPlugin = require(script.useIsStoryPlugin),
	useIsLocalPlugin = require(script.useIsLocalPlugin),
}
