local assets = {
	menu = {
		black = "rbxassetid://89737423754794",
		checkerboard = "rbxassetid://78612054048052",
		none = "rbxassetid://109437490397871",
		white = "rbxassetid://95419997577433",
	},
	processed = {
		dark = {
			["camera-plugin-button"] = "rbxassetid://78176835188672",
			["focus-plugin-action"] = "rbxassetid://79927009455662",
			["fullscreen-plugin-action"] = "rbxassetid://130771320706172",
			["gallery-plugin-button"] = "rbxassetid://116050068213742",
			["import-plugin-button"] = "rbxassetid://128075361252385",
			["serve-png-button"] = "rbxassetid://119342172787498",
			["ui-plugin-button"] = "rbxassetid://120984213805978",
		},
		light = {
			["camera-plugin-button"] = "rbxassetid://131054580832784",
			["focus-plugin-action"] = "rbxassetid://122278137825997",
			["fullscreen-plugin-action"] = "rbxassetid://134305674841615",
			["gallery-plugin-button"] = "rbxassetid://115826925245652",
			["import-plugin-button"] = "rbxassetid://103463040793452",
			["serve-png-button"] = "rbxassetid://127226900416614",
			["ui-plugin-button"] = "rbxassetid://125013376553663",
		},
	},
	scroll = {
		["scroll-bottom"] = "rbxassetid://100620450449275",
		["scroll-middle"] = "rbxassetid://103217370027697",
		["scroll-top"] = "rbxassetid://124043012203553",
	},
}

return assets