return {
	menu = {
		black = "rbxassetid://100163554161546",
		checkerboard = "rbxassetid://88124589937993",
		none = "rbxassetid://81132700836257",
		white = "rbxassetid://131575500647776",
	},
	processed = {
		dark = {
			["camera-plugin-button"] = "rbxassetid://131188633601831",
			["focus-plugin-action"] = "rbxassetid://78500258546917",
			["fullscreen-plugin-action"] = "rbxassetid://137233628303920",
			["gallery-plugin-button"] = "rbxassetid://73631418475004",
			["import-plugin-button"] = "rbxassetid://117524015648700",
			["ui-plugin-button"] = "rbxassetid://107602796794258",
		},
		light = {
			["camera-plugin-button"] = "rbxassetid://74699004820485",
			["focus-plugin-action"] = "rbxassetid://109521150602385",
			["fullscreen-plugin-action"] = "rbxassetid://112397251153211",
			["gallery-plugin-button"] = "rbxassetid://83204999559324",
			["import-plugin-button"] = "rbxassetid://140092277696411",
			["ui-plugin-button"] = "rbxassetid://98108830157071",
		},
	},
}
