return {
	dark = {
		["camera-plugin-button"] = "rbxassetid://80294457834748",
		["focus-plugin-action"] = "rbxassetid://94292196492522",
		["fullscreen-plugin-action"] = "rbxassetid://116060515334895",
		["gallery-plugin-button"] = "rbxassetid://139719769244755",
		["import-plugin-button"] = "rbxassetid://82213616882433",
		["ui-plugin-button"] = "rbxassetid://88868582278689",
	},
	light = {
		["camera-plugin-button"] = "rbxassetid://127193371371579",
		["focus-plugin-action"] = "rbxassetid://97859268696430",
		["fullscreen-plugin-action"] = "rbxassetid://103277114292455",
		["gallery-plugin-button"] = "rbxassetid://79123407406717",
		["import-plugin-button"] = "rbxassetid://102619977563512",
		["ui-plugin-button"] = "rbxassetid://118048838341065",
	},
}
