name: Update Place Version

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  update:
    name: Update Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Setup rokit"
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: "Run lune update script"
        run: |
          lune run update-place-version ${{ secrets.PHOTOBOOTH_PLACE_UPDATE_API_KEY }}
